/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package views;

import interfaces.HomeInterface;
import java.awt.Color;
import javax.swing.JButton;
import javax.swing.JLabel;

/**
 *
 * @author ASUS
 */
public class HomeView extends javax.swing.JFrame {

    /**
     * Creates new form MenuGameView
     */
    private HomeInterface homeInterface;

    public HomeView() {
        initComponents();
        this.setLocationRelativeTo(null);
        this.layerGameMode.setVisible(false);
        this.layerExit.setVisible(false);
        this.layerSetting.setVisible(false);
        this.layerTakeFirst.setVisible(false);
        this.setVisible(false);
    }

    public void setHomeActions(HomeInterface homeInterface) {
        this.homeInterface = homeInterface;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        layerTakeFirst = new javax.swing.JLayeredPane();
        btn_machineFirst = new javax.swing.JButton();
        btn_playerFirst = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        lb_machineFirst = new javax.swing.JLabel();
        lb_back1 = new javax.swing.JLabel();
        btn_back1 = new javax.swing.JButton();
        lb_playerFirst = new javax.swing.JLabel();
        layerGameMode = new javax.swing.JLayeredPane();
        btn_pvm = new javax.swing.JButton();
        btn_pvp = new javax.swing.JButton();
        btn_back = new javax.swing.JButton();
        lb_back = new javax.swing.JLabel();
        lb_pvp = new javax.swing.JLabel();
        lb_pvm = new javax.swing.JLabel();
        layerMenu = new javax.swing.JLayeredPane();
        btn_newgame = new javax.swing.JButton();
        btn_continue = new javax.swing.JButton();
        btn_setting = new javax.swing.JButton();
        btn_exit = new javax.swing.JButton();
        lb_Exit = new javax.swing.JLabel();
        lb_continue = new javax.swing.JLabel();
        lb_setting = new javax.swing.JLabel();
        lb_newgame = new javax.swing.JLabel();
        layerExit = new javax.swing.JLayeredPane();
        lb_exit = new javax.swing.JLabel();
        btn_yesExit = new javax.swing.JButton();
        btn_noExit = new javax.swing.JButton();
        lb_yes = new javax.swing.JLabel();
        lb_no = new javax.swing.JLabel();
        lb_backgroundExit = new javax.swing.JLabel();
        lb_gameNim = new javax.swing.JLabel();
        lb_logo = new javax.swing.JLabel();
        layerSetting = new javax.swing.JLayeredPane();
        lb_st = new javax.swing.JLabel();
        spn_maxRows = new javax.swing.JSpinner();
        spn_minRows = new javax.swing.JSpinner();
        spn_maxSticks = new javax.swing.JSpinner();
        spn_minSticks = new javax.swing.JSpinner();
        lb_minSticks1 = new javax.swing.JLabel();
        lb_maxRows1 = new javax.swing.JLabel();
        lb_minRows1 = new javax.swing.JLabel();
        btn_backAfterSet = new javax.swing.JButton();
        lb_maxSticks1 = new javax.swing.JLabel();
        btn_saveSet = new javax.swing.JButton();
        cbb_gameRules = new javax.swing.JComboBox<>();
        lb_gameRules1 = new javax.swing.JLabel();
        lb_erMinSticks = new javax.swing.JLabel();
        lb_erMinRows = new javax.swing.JLabel();
        lb_erMaxRows = new javax.swing.JLabel();
        lb_erMaxSticks = new javax.swing.JLabel();
        lb_backAfterSet = new javax.swing.JLabel();
        lb_saveSet = new javax.swing.JLabel();
        lb_background = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setLocation(new java.awt.Point(0, 0));
        setResizable(false);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        layerTakeFirst.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        btn_machineFirst.setFont(new java.awt.Font("Segoe UI Black", 0, 14)); // NOI18N
        btn_machineFirst.setText("Machine");
        btn_machineFirst.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        btn_machineFirst.setFocusPainted(false);
        btn_machineFirst.setBackground(Color.WHITE);
        btn_machineFirst.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btn_machineFirstMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btn_machineFirstMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btn_machineFirstMouseExited(evt);
            }
        });
        layerTakeFirst.add(btn_machineFirst, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 60, 90, -1));

        btn_playerFirst.setFont(new java.awt.Font("Segoe UI Black", 0, 14)); // NOI18N
        btn_playerFirst.setText("You");
        btn_playerFirst.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        btn_playerFirst.setFocusPainted(false);
        btn_playerFirst.setBackground(Color.WHITE);
        btn_playerFirst.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btn_playerFirstMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btn_playerFirstMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btn_playerFirstMouseExited(evt);
            }
        });
        layerTakeFirst.add(btn_playerFirst, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 100, 90, -1));

        jLabel1.setFont(new java.awt.Font("Segoe UI Black", 0, 14)); // NOI18N
        jLabel1.setText("Who takes first?");
        layerTakeFirst.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 20, -1, -1));

        lb_machineFirst.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/VECTOR.png"))); // NOI18N
        lb_machineFirst.setVisible(false);
        layerTakeFirst.add(lb_machineFirst, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 60, -1, -1));

        lb_back1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/VECTOR.png"))); // NOI18N
        lb_back1.setVisible(false);
        layerTakeFirst.add(lb_back1, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 160, -1, -1));

        btn_back1.setFont(new java.awt.Font("Segoe UI Black", 0, 14)); // NOI18N
        btn_back1.setText("Back");
        btn_back1.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        btn_back1.setFocusPainted(false);
        btn_back1.setBackground(Color.WHITE);
        btn_back1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btn_back1MouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btn_back1MouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btn_back1MouseExited(evt);
            }
        });
        layerTakeFirst.add(btn_back1, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 160, 90, -1));

        lb_playerFirst.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/VECTOR.png"))); // NOI18N
        lb_playerFirst.setVisible(false);
        layerTakeFirst.add(lb_playerFirst, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 100, -1, -1));

        getContentPane().add(layerTakeFirst, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 160, 260, 230));

        layerGameMode.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        btn_pvm.setBackground(Color.WHITE);
        btn_pvm.setFont(new java.awt.Font("Segoe UI Black", 0, 12)); // NOI18N
        btn_pvm.setText("Player VS Machine");
        btn_pvm.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        btn_pvm.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btn_pvm.setFocusPainted(false);
        btn_pvm.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btn_pvmMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btn_pvmMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btn_pvmMouseExited(evt);
            }
        });
        layerGameMode.add(btn_pvm, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 60, 150, -1));

        btn_pvp.setBackground(Color.WHITE);
        btn_pvp.setFont(new java.awt.Font("Segoe UI Black", 0, 12)); // NOI18N
        btn_pvp.setText("Player VS Player");
        btn_pvp.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        btn_pvp.setFocusPainted(false);
        btn_pvp.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btn_pvpMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btn_pvpMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btn_pvpMouseExited(evt);
            }
        });
        layerGameMode.add(btn_pvp, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 20, 150, -1));

        btn_back.setBackground(Color.WHITE);
        btn_back.setFont(new java.awt.Font("Segoe UI Black", 0, 12)); // NOI18N
        btn_back.setText("Back");
        btn_back.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        btn_back.setFocusPainted(false);
        btn_back.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btn_backMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btn_backMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btn_backMouseExited(evt);
            }
        });
        layerGameMode.add(btn_back, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 130, 70, -1));

        lb_back.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/VECTOR.png"))); // NOI18N
        lb_back.setVisible(false);
        layerGameMode.add(lb_back, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 130, -1, -1));

        lb_pvp.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/VECTOR.png"))); // NOI18N
        lb_pvp.setVisible(false);
        layerGameMode.add(lb_pvp, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 20, -1, -1));

        lb_pvm.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/VECTOR.png"))); // NOI18N
        lb_pvm.setVisible(false);
        layerGameMode.add(lb_pvm, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 60, -1, -1));

        getContentPane().add(layerGameMode, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 180, 240, -1));

        layerMenu.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        btn_newgame.setBackground(Color.WHITE);
        btn_newgame.setFont(new java.awt.Font("Segoe UI Black", 0, 12)); // NOI18N
        btn_newgame.setText("NEW GAME");
        btn_newgame.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        btn_newgame.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btn_newgame.setFocusPainted(false);
        btn_newgame.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btn_newgameMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btn_newgameMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btn_newgameMouseExited(evt);
            }
        });
        layerMenu.add(btn_newgame, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 60, 110, -1));

        btn_continue.setBackground(Color.WHITE);
        btn_continue.setFont(new java.awt.Font("Segoe UI Black", 0, 12)); // NOI18N
        btn_continue.setText("CONTINUE");
        btn_continue.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        btn_continue.setFocusPainted(false);
        btn_continue.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btn_continueMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btn_continueMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btn_continueMouseExited(evt);
            }
        });
        layerMenu.add(btn_continue, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 20, 110, -1));

        btn_setting.setBackground(Color.WHITE);
        btn_setting.setFont(new java.awt.Font("Segoe UI Black", 0, 12)); // NOI18N
        btn_setting.setText("SETTING");
        btn_setting.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        btn_setting.setFocusable(false);
        btn_setting.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btn_settingMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btn_settingMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btn_settingMouseExited(evt);
            }
        });
        layerMenu.add(btn_setting, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 100, 110, -1));

        btn_exit.setBackground(Color.WHITE);
        btn_exit.setFont(new java.awt.Font("Segoe UI Black", 0, 12)); // NOI18N
        btn_exit.setText("EXIT");
        btn_exit.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        btn_exit.setFocusPainted(false);
        btn_exit.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btn_exitMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btn_exitMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btn_exitMouseExited(evt);
            }
        });
        layerMenu.add(btn_exit, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 140, 110, -1));

        lb_Exit.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/VECTOR.png"))); // NOI18N
        lb_Exit.setVisible(false);
        layerMenu.add(lb_Exit, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 140, -1, -1));

        lb_continue.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/VECTOR.png"))); // NOI18N
        lb_continue.setVisible(false);
        layerMenu.add(lb_continue, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 20, -1, -1));

        lb_setting.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/VECTOR.png"))); // NOI18N
        lb_setting.setVisible(false);
        layerMenu.add(lb_setting, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 100, -1, -1));

        lb_newgame.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/VECTOR.png"))); // NOI18N
        lb_newgame.setVisible(false);
        layerMenu.add(lb_newgame, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 60, -1, -1));

        getContentPane().add(layerMenu, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 180, 200, 190));

        layerExit.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        lb_exit.setFont(new java.awt.Font("Segoe UI Black", 0, 14)); // NOI18N
        lb_exit.setText("<html>Do you really want to exit <br>  the game? </html>");
        layerExit.add(lb_exit, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 20, 280, 60));

        btn_yesExit.setBackground(Color.WHITE);
        btn_yesExit.setFont(new java.awt.Font("Segoe UI Black", 0, 14)); // NOI18N
        btn_yesExit.setText("Yes");
        btn_yesExit.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        btn_yesExit.setFocusPainted(false);
        btn_yesExit.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btn_yesExitMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btn_yesExitMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btn_yesExitMouseExited(evt);
            }
        });
        layerExit.add(btn_yesExit, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 160, 60, -1));

        btn_noExit.setBackground(Color.WHITE);
        btn_noExit.setFont(new java.awt.Font("Segoe UI Black", 0, 14)); // NOI18N
        btn_noExit.setText("No");
        btn_noExit.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        btn_noExit.setFocusPainted(false);
        btn_noExit.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btn_noExitMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btn_noExitMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btn_noExitMouseExited(evt);
            }
        });
        layerExit.add(btn_noExit, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 110, 60, -1));

        lb_yes.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/VECTOR.png"))); // NOI18N
        lb_yes.setVisible(false);
        layerExit.add(lb_yes, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 160, -1, -1));

        lb_no.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/VECTOR.png"))); // NOI18N
        lb_no.setVisible(false);
        layerExit.add(lb_no, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 110, -1, -1));

        lb_backgroundExit.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/BACKGROUND_NOTIFICATION.png"))); // NOI18N
        layerExit.add(lb_backgroundExit, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 270, 270));

        getContentPane().add(layerExit, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 170, 240, 260));

        lb_gameNim.setFont(new java.awt.Font("Segoe UI Black", 0, 18)); // NOI18N
        lb_gameNim.setText("GAME NIM");
        getContentPane().add(lb_gameNim, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 120, -1, -1));

        lb_logo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/logo.png"))); // NOI18N
        getContentPane().add(lb_logo, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 30, -1, -1));

        layerSetting.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        lb_st.setFont(new java.awt.Font("Segoe UI Black", 0, 14)); // NOI18N
        lb_st.setText("SETTING");
        layerSetting.add(lb_st, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 20, -1, -1));
        layerSetting.add(spn_maxRows, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 100, 50, -1));
        layerSetting.add(spn_minRows, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 70, 50, -1));
        layerSetting.add(spn_maxSticks, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 160, 50, -1));
        layerSetting.add(spn_minSticks, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 130, 50, -1));

        lb_minSticks1.setText("Minimum Sticks");
        layerSetting.add(lb_minSticks1, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 130, -1, -1));

        lb_maxRows1.setText("Maximum Rows");
        layerSetting.add(lb_maxRows1, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 100, -1, -1));

        lb_minRows1.setText("Minimum Rows");
        layerSetting.add(lb_minRows1, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 70, -1, -1));

        btn_backAfterSet.setText("Back");
        btn_backAfterSet.setFocusPainted(false);
        btn_backAfterSet.setBackground(Color.WHITE);
        btn_backAfterSet.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btn_backAfterSetMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btn_backAfterSetMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btn_backAfterSetMouseExited(evt);
            }
        });
        layerSetting.add(btn_backAfterSet, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 250, -1, -1));

        lb_maxSticks1.setText("Maximum Sticks");
        layerSetting.add(lb_maxSticks1, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 160, -1, -1));

        btn_saveSet.setText("Save");
        btn_saveSet.setFocusPainted(false);
        btn_saveSet.setBackground(Color.WHITE);
        btn_saveSet.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btn_saveSetMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btn_saveSetMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btn_saveSetMouseExited(evt);
            }
        });
        layerSetting.add(btn_saveSet, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 250, -1, -1));

        cbb_gameRules.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Normal Play", "Misère Play" }));
        layerSetting.add(cbb_gameRules, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 190, 100, -1));

        lb_gameRules1.setText("Game Rules");
        layerSetting.add(lb_gameRules1, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 190, -1, -1));

        lb_erMinSticks.setFont(new java.awt.Font("Segoe UI", 2, 14)); // NOI18N
        lb_erMinSticks.setForeground(java.awt.Color.red);
        lb_erMinSticks.setText("Value > 0 ");
        layerSetting.add(lb_erMinSticks, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 130, -1, -1));
        lb_erMinSticks.setVisible(false);

        lb_erMinRows.setFont(new java.awt.Font("Segoe UI", 2, 14)); // NOI18N
        lb_erMinRows.setForeground(java.awt.Color.red);
        lb_erMinRows.setText("Value > 0 ");
        layerSetting.add(lb_erMinRows, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 70, -1, -1));
        lb_erMinRows.setVisible(false);

        lb_erMaxRows.setFont(new java.awt.Font("Segoe UI", 2, 14)); // NOI18N
        lb_erMaxRows.setForeground(java.awt.Color.red);
        lb_erMaxRows.setText("Value > Min");
        layerSetting.add(lb_erMaxRows, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 100, -1, -1));
        lb_erMaxRows.setVisible(false);

        lb_erMaxSticks.setFont(new java.awt.Font("Segoe UI", 2, 14)); // NOI18N
        lb_erMaxSticks.setForeground(java.awt.Color.red);
        lb_erMaxSticks.setText("Value > Min");
        layerSetting.add(lb_erMaxSticks, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 160, -1, -1));
        lb_erMaxSticks.setVisible(false);

        lb_backAfterSet.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/arrow.png"))); // NOI18N
        lb_backAfterSet.setVisible(false);
        layerSetting.add(lb_backAfterSet, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 250, -1, -1));

        lb_saveSet.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/arrow.png"))); // NOI18N
        lb_saveSet.setVisible(false);
        layerSetting.add(lb_saveSet, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 250, -1, -1));

        getContentPane().add(layerSetting, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 140, 300, 290));

        lb_background.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/BACKGROUND.png"))); // NOI18N
        getContentPane().add(lb_background, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btn_newgameMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_newgameMouseClicked
        // TODO add your handling code here:
        this.layerGameMode.setVisible(true);
        this.layerMenu.setVisible(false);

    }//GEN-LAST:event_btn_newgameMouseClicked

    private void backHome() {
        this.layerTakeFirst.setVisible(false);
        this.layerGameMode.setVisible(false);
        this.layerMenu.setVisible(true);
    }

    private void btn_backMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_backMouseClicked
        // TODO add your handling code here:
        backHome();
    }//GEN-LAST:event_btn_backMouseClicked

    private void btn_pvpMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_pvpMouseClicked
        // TODO add your handling code here:
        homeInterface.NewGamePvP();
        backHome();
    }//GEN-LAST:event_btn_pvpMouseClicked

    private void btn_pvmMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_pvmMouseClicked
        // TODO add your handling code here:
        layerTakeFirst.setVisible(true);
        layerGameMode.setVisible(false);
    }//GEN-LAST:event_btn_pvmMouseClicked

    private void btn_continueMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_continueMouseClicked
        // TODO add your handling code here:
        homeInterface.Continue();
    }//GEN-LAST:event_btn_continueMouseClicked

    private void btn_exitMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_exitMouseClicked
        // TODO add your handling code here:
        layerExit.setVisible(true);
        layerMenu.setVisible(false);
    }//GEN-LAST:event_btn_exitMouseClicked

    private void btn_noExitMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_noExitMouseClicked
        // TODO add your handling code here:
        backHome();
    }//GEN-LAST:event_btn_noExitMouseClicked

    private void btn_yesExitMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_yesExitMouseClicked
        // TODO add your handling code here:
        System.exit(0);
    }//GEN-LAST:event_btn_yesExitMouseClicked

    private void btnMouseEntered(JButton btn, JLabel lbVector) {
        btn.setBackground(Color.ORANGE);
        lbVector.setVisible(true);
    }

    private void btnMouseExited(JButton btn, JLabel lbVector) {
        btn.setBackground(Color.WHITE);
        lbVector.setVisible(false);
    }

    private void btn_pvmMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_pvmMouseEntered
        // TODO add your handling code here:
        btnMouseEntered(btn_pvm, lb_pvm);
    }//GEN-LAST:event_btn_pvmMouseEntered

    private void btn_pvmMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_pvmMouseExited
        // TODO add your handling code here:
        btnMouseExited(btn_pvm, lb_pvm);
    }//GEN-LAST:event_btn_pvmMouseExited

    private void btn_pvpMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_pvpMouseEntered
        // TODO add your handling code here:
        btnMouseEntered(btn_pvp, lb_pvp);
    }//GEN-LAST:event_btn_pvpMouseEntered

    private void btn_backMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_backMouseEntered
        // TODO add your handling code here:
        btnMouseEntered(btn_back, lb_back);
    }//GEN-LAST:event_btn_backMouseEntered

    private void btn_backMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_backMouseExited
        // TODO add your handling code here:
        btnMouseExited(btn_back, lb_back);
    }//GEN-LAST:event_btn_backMouseExited

    private void btn_newgameMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_newgameMouseEntered
        // TODO add your handling code here:
        btnMouseEntered(btn_newgame, lb_newgame);
    }//GEN-LAST:event_btn_newgameMouseEntered

    private void btn_newgameMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_newgameMouseExited
        // TODO add your handling code here:
        btnMouseExited(btn_newgame, lb_newgame);
    }//GEN-LAST:event_btn_newgameMouseExited

    private void btn_continueMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_continueMouseEntered
        // TODO add your handling code here:
        btnMouseEntered(btn_continue, lb_continue);
    }//GEN-LAST:event_btn_continueMouseEntered

    private void btn_continueMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_continueMouseExited
        // TODO add your handling code here:
        btnMouseExited(btn_continue, lb_continue);
    }//GEN-LAST:event_btn_continueMouseExited

    private void btn_settingMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_settingMouseEntered
        // TODO add your handling code here:
        btnMouseEntered(btn_setting, lb_setting);
    }//GEN-LAST:event_btn_settingMouseEntered

    private void btn_settingMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_settingMouseExited
        // TODO add your handling code here:
        btnMouseExited(btn_setting, lb_setting);
    }//GEN-LAST:event_btn_settingMouseExited

    private void btn_exitMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_exitMouseEntered
        // TODO add your handling code here:
        btnMouseEntered(btn_exit, lb_Exit);
    }//GEN-LAST:event_btn_exitMouseEntered

    private void btn_exitMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_exitMouseExited
        // TODO add your handling code here:
        btnMouseExited(btn_exit, lb_Exit);
    }//GEN-LAST:event_btn_exitMouseExited

    private void btn_yesExitMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_yesExitMouseEntered
        // TODO add your handling code here:
        btnMouseEntered(btn_yesExit, lb_yes);
    }//GEN-LAST:event_btn_yesExitMouseEntered

    private void btn_yesExitMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_yesExitMouseExited
        // TODO add your handling code here:
        btnMouseExited(btn_yesExit, lb_yes);
    }//GEN-LAST:event_btn_yesExitMouseExited

    private void btn_noExitMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_noExitMouseEntered
        // TODO add your handling code here:
        btnMouseEntered(btn_noExit, lb_no);
    }//GEN-LAST:event_btn_noExitMouseEntered

    private void btn_noExitMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_noExitMouseExited
        // TODO add your handling code here:
        btnMouseExited(btn_noExit, lb_no);
    }//GEN-LAST:event_btn_noExitMouseExited

    private void btn_pvpMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_pvpMouseExited
        // TODO add your handling code here:
        btnMouseExited(btn_pvp, lb_pvp);
    }//GEN-LAST:event_btn_pvpMouseExited

    private void btn_settingMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_settingMouseClicked
        // TODO add your handling code here:
        this.layerSetting.setVisible(true);
        this.layerMenu.setVisible(false);
    }//GEN-LAST:event_btn_settingMouseClicked

    private void btn_backAfterSetMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_backAfterSetMouseClicked
        // TODO add your handling code here:
        this.layerSetting.setVisible(false);
        this.layerMenu.setVisible(true);
    }//GEN-LAST:event_btn_backAfterSetMouseClicked

    private void btn_saveSetMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_saveSetMouseClicked
        // TODO add your handling code here:
        // Lấy giá trị từ các spinner
        int maxRows = Integer.parseInt(spn_maxRows.getValue().toString());
        int minRows = Integer.parseInt(spn_minRows.getValue().toString());
        int maxSticks = Integer.parseInt(spn_maxSticks.getValue().toString());
        int minSticks = Integer.parseInt(spn_minSticks.getValue().toString());
        Boolean isNormalPlay = (cbb_gameRules.getSelectedIndex() == 0);

        // Xóa thông báo lỗi
        lb_erMinRows.setVisible(false);
        lb_erMaxRows.setVisible(false);
        lb_erMinSticks.setVisible(false);
        lb_erMaxSticks.setVisible(false);

        // Kiểm tra giá trị đầu vào
        boolean isValid = true;

        if (minRows <= 0) {
            lb_erMinRows.setVisible(true);
            isValid = false; // Đánh dấu giá trị không hợp lệ
        }
        if (maxRows < minRows) {
            lb_erMaxRows.setVisible(true);
            isValid = false; // Đánh dấu giá trị không hợp lệ
        }
        if (minSticks <= 0) {
            lb_erMinSticks.setVisible(true);
            isValid = false; // Đánh dấu giá trị không hợp lệ
        }
        if (maxSticks < minSticks) {
            lb_erMaxSticks.setVisible(true);
            isValid = false; // Đánh dấu giá trị không hợp lệ
        }

        // Chỉ xử lí nêu các giá trị đều hợp lệ
        if (isValid) {
            homeInterface.SaveSetting(maxRows, minRows, maxSticks, minSticks, isNormalPlay);
            this.layerSetting.setVisible(false);
            this.layerMenu.setVisible(true);
        }
    }//GEN-LAST:event_btn_saveSetMouseClicked

    private void btn_saveSetMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_saveSetMouseEntered
        // TODO add your handling code here:
        btnMouseEntered(btn_saveSet, lb_saveSet);
    }//GEN-LAST:event_btn_saveSetMouseEntered

    private void btn_saveSetMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_saveSetMouseExited
        // TODO add your handling code here:
        btnMouseExited(btn_saveSet, lb_saveSet);
    }//GEN-LAST:event_btn_saveSetMouseExited

    private void btn_backAfterSetMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_backAfterSetMouseEntered
        // TODO add your handling code here:
        btnMouseEntered(btn_backAfterSet, lb_backAfterSet);
    }//GEN-LAST:event_btn_backAfterSetMouseEntered

    private void btn_backAfterSetMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_backAfterSetMouseExited
        // TODO add your handling code here:
        btnMouseExited(btn_backAfterSet, lb_backAfterSet);
    }//GEN-LAST:event_btn_backAfterSetMouseExited

    private void btn_machineFirstMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_machineFirstMouseEntered
        // TODO add your handling code here:
        btnMouseEntered(btn_machineFirst, lb_machineFirst);
    }//GEN-LAST:event_btn_machineFirstMouseEntered

    private void btn_machineFirstMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_machineFirstMouseExited
        // TODO add your handling code here:
        btnMouseExited(btn_machineFirst, lb_machineFirst);
    }//GEN-LAST:event_btn_machineFirstMouseExited

    private void btn_playerFirstMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_playerFirstMouseEntered
        // TODO add your handling code here:
        btnMouseEntered(btn_playerFirst, lb_playerFirst);
    }//GEN-LAST:event_btn_playerFirstMouseEntered

    private void btn_playerFirstMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_playerFirstMouseExited
        // TODO add your handling code here:
        btnMouseExited(btn_playerFirst, lb_playerFirst);
    }//GEN-LAST:event_btn_playerFirstMouseExited

    private void btn_back1MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_back1MouseEntered
        // TODO add your handling code here:
        btnMouseEntered(btn_back1, lb_back1);
    }//GEN-LAST:event_btn_back1MouseEntered

    private void btn_back1MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_back1MouseExited
        // TODO add your handling code here:
        btnMouseExited(btn_back1, lb_back1);
    }//GEN-LAST:event_btn_back1MouseExited

    private void btn_machineFirstMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_machineFirstMouseClicked
        // TODO add your handling code here:
        homeInterface.NewGamePvM(false);
        backHome();
    }//GEN-LAST:event_btn_machineFirstMouseClicked

    private void btn_playerFirstMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_playerFirstMouseClicked
        // TODO add your handling code here:
        homeInterface.NewGamePvM(true);
        backHome();
    }//GEN-LAST:event_btn_playerFirstMouseClicked

    private void btn_back1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_back1MouseClicked
        // TODO add your handling code here:
        this.backHome();
    }//GEN-LAST:event_btn_back1MouseClicked

    public void setSetting(int maxRows, int minRows, int maxSticks, int minSticks, Boolean normalPlay) {
        // Đặt giá trị cho spinner
        spn_maxRows.setValue(maxRows);
        spn_minRows.setValue(minRows);
        spn_maxSticks.setValue(maxSticks);
        spn_minSticks.setValue(minSticks);

        // Đặt index 0 nếu là "Normal Play" and index 1 nếu là "Misère Play"
        cbb_gameRules.setSelectedIndex(normalPlay ? 0 : 1);
    }

    // 
    public void setContinue(boolean canContinue) { //Chỉ tiếp tục nếu có ván game được lưu trước đó
        if (canContinue) {
            btn_continue.setVisible(true);
        } else {
            btn_continue.setVisible(false);
        }
    }

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(HomeView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(HomeView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(HomeView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(HomeView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new HomeView().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btn_back;
    private javax.swing.JButton btn_back1;
    private javax.swing.JButton btn_backAfterSet;
    private javax.swing.JButton btn_continue;
    private javax.swing.JButton btn_exit;
    private javax.swing.JButton btn_machineFirst;
    private javax.swing.JButton btn_newgame;
    private javax.swing.JButton btn_noExit;
    private javax.swing.JButton btn_playerFirst;
    private javax.swing.JButton btn_pvm;
    private javax.swing.JButton btn_pvp;
    private javax.swing.JButton btn_saveSet;
    private javax.swing.JButton btn_setting;
    private javax.swing.JButton btn_yesExit;
    private javax.swing.JComboBox<String> cbb_gameRules;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLayeredPane layerExit;
    private javax.swing.JLayeredPane layerGameMode;
    private javax.swing.JLayeredPane layerMenu;
    private javax.swing.JLayeredPane layerSetting;
    private javax.swing.JLayeredPane layerTakeFirst;
    private javax.swing.JLabel lb_Exit;
    private javax.swing.JLabel lb_back;
    private javax.swing.JLabel lb_back1;
    private javax.swing.JLabel lb_backAfterSet;
    private javax.swing.JLabel lb_background;
    private javax.swing.JLabel lb_backgroundExit;
    private javax.swing.JLabel lb_continue;
    private javax.swing.JLabel lb_erMaxRows;
    private javax.swing.JLabel lb_erMaxSticks;
    private javax.swing.JLabel lb_erMinRows;
    private javax.swing.JLabel lb_erMinSticks;
    private javax.swing.JLabel lb_exit;
    private javax.swing.JLabel lb_gameNim;
    private javax.swing.JLabel lb_gameRules1;
    private javax.swing.JLabel lb_logo;
    private javax.swing.JLabel lb_machineFirst;
    private javax.swing.JLabel lb_maxRows1;
    private javax.swing.JLabel lb_maxSticks1;
    private javax.swing.JLabel lb_minRows1;
    private javax.swing.JLabel lb_minSticks1;
    private javax.swing.JLabel lb_newgame;
    private javax.swing.JLabel lb_no;
    private javax.swing.JLabel lb_playerFirst;
    private javax.swing.JLabel lb_pvm;
    private javax.swing.JLabel lb_pvp;
    private javax.swing.JLabel lb_saveSet;
    private javax.swing.JLabel lb_setting;
    private javax.swing.JLabel lb_st;
    private javax.swing.JLabel lb_yes;
    private javax.swing.JSpinner spn_maxRows;
    private javax.swing.JSpinner spn_maxSticks;
    private javax.swing.JSpinner spn_minRows;
    private javax.swing.JSpinner spn_minSticks;
    // End of variables declaration//GEN-END:variables

}
